10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
array_2x2 = np.empty((2, 2))
print(array_2x2)


[[-2.    1.  ]
 [ 1.75 -0.75]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
array_4x2 = np.ones((4, 2))
print(array_4x2)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
shape = (3, 3)  # Example shape
fill_value = 7  # Example fill value
dtype = int  # Example data type

# Create the array
array_filled = np.full(shape, fill_value, dtype=dtype)

print(array_filled)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
given_array = np.array([[4, 5, 6], [7, 8, 9]])

# Create a new array of zeros with the same shape and type
zeros_array = np.zeros_like(given_array)

print(zeros_array)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
given_array = np.array([[2, 3, 4], [5, 6, 7]])

# Create a new array of ones with the same shape and type
ones_array = np.ones_like(given_array)

print(ones_array)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]

# Convert to NumPy array
numpy_array = np.array(new_list)

print(numpy_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array_range = np.arange(10, 50)

print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
array_1D = np.arange(9)

# Reshape it into a 3x3 matrix
matrix_3x3 = array_1D.reshape(3, 3)

print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.

{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)

# Find the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)

Random Array: [0.6070393  0.53381024 0.39459106 0.56820334 0.56616452 0.80967788
 0.10337432 0.04545956 0.84745705 0.0587387  0.76514131 0.38560629
 0.2132198  0.62392539 0.73337696 0.3933357  0.91038071 0.54778652
 0.20761634 0.06682177 0.77472374 0.09573329 0.86088089 0.66402762
 0.15286836 0.29072558 0.44230171 0.37927345 0.28478594 0.97957914]
Mean of the Array: 0.4768875491092504


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()

print("Random 10x10 Array:")
print(random_array_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array:
[[0.75634967 0.36313737 0.51987563 0.93537425 0.21025813 0.66612503
  0.72039572 0.60834174 0.5438648  0.39519584]
 [0.94244224 0.62261501 0.58421236 0.46131089 0.76116839 0.30513002
  0.48098569 0.92660276 0.62380638 0.78679349]
 [0.2825149  0.78931198 0.85542323 0.87417045 0.49856884 0.984713
  0.50987444 0.12150999 0.18941781 0.46806851]
 [0.47989264 0.91432182 0.93743375 0.72682088 0.95626752 0.12845855
  0.04185061 0.43825872 0.65708565 0.00968363]
 [0.39307163 0.71580717 0.27015279 0.53788938 0.56035653 0.86542609
  0.6053137  0.54384046 0.03301383 0.3735356 ]
 [0.48622264 0.58902566 0.97705024 0.71782187 0.76410195 0.63165302
  0.75341611 0.16220766 0.31383265 0.04091852]
 [0.23133904 0.70756542 0.83064166 0.4750927  0.53866128 0.6949684
  0.84556333 0.6442708  0.15804148 0.02724368]
 [0.20740551 0.61364881 0.69617052 0.11041845 0.2718544  0.99565368
  0.12630804 0.31713191 0.35433585 0.7531539 ]
 [0.95613445 0.71126884 0.5533748  0.14558836 0.92870676 0.9760

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1, 2, 0, 0, 4, 0]

# Reverse the array
reversed_array = arr[::-1]

print(reversed_array)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
size = 5

# Create a 2D array filled with zeros
array = np.zeros((size, size))

# Set the border to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8))

# Fill the matrix with a checkerboard pattern (alternating 1s and 0s)
checkerboard[1::2, ::2] = 1  # Fill odd rows with 1s at even columns
checkerboard[::2, 1::2] = 1  # Fill even rows with 1s at odd columns

print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
sum_array = np.add(x, y)

print(sum_array)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Subtract the two arrays
difference_array = np.subtract(x, y)

print(difference_array)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
x = np.array([[1, 2], [3, 5]])

# Multiply the array by 3
product_array = x * 3

print(product_array)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
x = np.array([[1, 2], [3, 5]])

# Square each element of the array
squared_array = np.square(x)

print(squared_array)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Dot product between v and w
dot_vw = np.dot(v, w)

# Dot product between x and v (matrix and vector)
dot_xv = np.dot(x, v)

# Dot product between x and y (matrix and matrix)
dot_xy = np.dot(x, y)

print("Dot product between v and w:", dot_vw)
print("Dot product between x and v:", dot_xv)
print("Dot product between x and y:", dot_xy)

Dot product between v and w: 219
Dot product between x and v: [29 77]
Dot product between x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.

{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Concatenate x and y along rows (axis=0)
concat_xy_rows = np.concatenate((x, y), axis=0)

# Concatenate v and w along columns (first, reshape v and w to column vectors)
v_reshaped = v.reshape(-1, 1)  # Reshape v to a column vector
w_reshaped = w.reshape(-1, 1)  # Reshape w to a column vector
concat_vw_columns = np.concatenate((v_reshaped, w_reshaped), axis=1)

print("Concatenated x and y along rows:")
print(concat_xy_rows)

print("\nConcatenated v and w along columns:")
print(concat_vw_columns)

Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Attempt to concatenate x and v along rows
try:
    concat_xv_rows = np.concatenate((x, v), axis=0)  # This will raise an error
except Exception as e:
    print("Error during concatenation along rows:", e)

# Attempt to concatenate x and v along columns
try:
    concat_xv_columns = np.concatenate((x, v), axis=1)  # This will also raise an error
except Exception as e:
    print("Error during concatenation along columns:", e)


Error during concatenation along rows: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Error during concatenation along columns: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


When you try to concatenate them along rows (stack them vertically), v is just a single row (1D), and x has 2 rows, so they don't match in dimensions.

When you try to concatenate them along columns (stack them horizontally), v is 1D and doesn't have the same number of rows as x, so they don’t align properly.

Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.A−1 = I.

In [ ]:

# Given matrix A
A = np.array([[3, 4], [7, 8]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
result = np.dot(A, A_inv)

# Print the result (should be the identity matrix)
print("A * A^-1 =")
print(result)

# The identity matrix for comparison
I = np.eye(2)
print("\nIdentity matrix I:")
print(I)


A * A^-1 =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
[[1. 0.]
 [0. 1.]]


2. Prove AB ̸= BA.

In [ ]:
# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Calculate AB
AB = np.dot(A, B)

# Calculate BA
BA = np.dot(B, A)

# Print both results
print("AB =")
print(AB)

print("\nBA =")
print(BA)

# Check if AB is equal to BA
if np.array_equal(AB, BA):
    print("\nAB equals BA.")
else:
    print("\nAB does not equal BA.")

AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

AB does not equal BA.


3. Prove (AB)

T = BTAT

In [ ]:
# Given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Calculate (AB)^T
AB_transpose = np.transpose(np.dot(A, B))

# Calculate B^T A^T
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)

# Print both results
print("(AB)^T =")
print(AB_transpose)

print("\nB^T A^T =")
print(BT_AT)

# Check if they are equal
if np.array_equal(AB_transpose, BT_AT):
    print("\n(AB)^T equals B^T A^T.")
else:
    print("\n(AB)^T does not equal B^T A^T.")

(AB)^T =
[[23 51]
 [13 29]]

B^T A^T =
[[23 51]
 [13 29]]

(AB)^T equals B^T A^T.


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the formula X = A^-1 * B
X = np.dot(A_inv, B)

print("Solution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.

{Explore more about ”linalg” function of Numpy}

In [ ]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([-1, -3, 9])

# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solve for X by multiplying the inverse of A with B
X = np.dot(A_inv, B)

# Print the solution for x, y, z
print("Solution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays.
Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000.

  Measure and Print the time taken for this operation.



In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

# Measure time for element-wise addition using Python Lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()

# Calculate and print the time taken
list_time = end_time - start_time
print(f"Time taken for element-wise addition using Python Lists: {list_time:.6f} seconds")


Time taken for element-wise addition using Python Lists: 0.197296 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

# Measure time for element-wise addition using NumPy Arrays
start_time = time.time()
array_sum = array1 + array2
end_time = time.time()

# Calculate and print the time taken
numpy_time = end_time - start_time
print(f"Time taken for element-wise addition using NumPy Arrays: {numpy_time:.6f} seconds")


Time taken for element-wise addition using NumPy Arrays: 0.007199 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

# Measure time for element-wise multiplication using Python Lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()

# Calculate and print the time taken
list_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Python Lists: {list_time:.6f} seconds")


Time taken for element-wise multiplication using Python Lists: 0.174633 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

# Measure time for element-wise multiplication using NumPy Arrays
start_time = time.time()
array_product = array1 * array2
end_time = time.time()

# Calculate and print the time taken
numpy_time = end_time - start_time
print(f"Time taken for element-wise multiplication using NumPy Arrays: {numpy_time:.6f} seconds")


Time taken for element-wise multiplication using NumPy Arrays: 0.003664 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

# Measure time for dot product calculation using Python Lists
start_time = time.time()

# Dot product calculation using list comprehension
dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

end_time = time.time()

# Calculate and print the time taken
list_time = end_time - start_time
print(f"Time taken for dot product using Python Lists: {list_time:.6f} seconds")


Time taken for dot product using Python Lists: 0.097905 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

# Measure time for dot product calculation using NumPy Arrays
start_time = time.time()

# Dot product calculation using NumPy's optimized dot function
dot_product = np.dot(array1, array2)

end_time = time.time()

# Calculate and print the time taken
numpy_time = end_time - start_time
print(f"Time taken for dot product using NumPy Arrays: {numpy_time:.6f} seconds")


Time taken for dot product using NumPy Arrays: 0.001749 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time

# Create two matrices of size 1000x1000
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

# Measure time for matrix multiplication using Python Lists
start_time = time.time()

# Matrix multiplication using nested loops
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

end_time = time.time()

# Calculate and print the time taken
list_time = end_time - start_time
print(f"Time taken for matrix multiplication using Python Lists: {list_time:.6f} seconds")


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create two NumPy arrays of size 1000x1000
matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)

# Measure time for matrix multiplication using NumPy
start_time = time.time()

# Matrix multiplication using NumPy's dot function
result_matrix = np.dot(matrix1, matrix2)

# Alternatively, you can use the @ operator as well
# result_matrix = matrix1 @ matrix2

end_time = time.time()

# Calculate and print the time taken
numpy_time = end_time - start_time
print(f"Time taken for matrix multiplication using NumPy: {numpy_time:.6f} seconds")
